### ISSUE TITLE
Rewrite in flutter

### ISSUE THREAD

**Issue by amichaelyu** [pmxi/qr#6]
Woo-hoo
Todo for 2022

**Comment by amb2127** [comment]
shut up

**Comment by amichaelyu** [comment]
This better be done for release 2.0

**Comment by pmxi** [comment]
Then there will be no 2.0. it will just be 1. forever

**Comment by amichaelyu** [comment]
I am not a front end developer. I only write backend. Find someone else to write flutter or electron.

- [ ] Find someone who likes flutter or electron

**Comment by amb2127** [comment]
you're going to have an issue with that

**Comment by pmxi** [comment]
maybe you could help
